#!/bin/sh

bunx concurrently \
  --kill-others-on-fail \
  --prefix "[{name}]" \
  --names "test,lint,typecheck,build" \
  --prefix-colors "bgRed.bold.white,bgGreen.bold.white,bgBlue.bold.white,bgMagenta.bold.white" \
    "bun run test --silent -- --watch=false" \
    "bun run lint --silent" \
    "bun run typecheck --silent" \
    "bun run build --silent"
