#!/bin/sh

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(dirname "$script_dir")

bunx concurrently \
  --kill-others-on-fail \
  --prefix "[{name}]" \
  --names "test,lint,typecheck,build" \
  --prefix-colors "bgRed.bold.white,bgGreen.bold.white,bgBlue.bold.white,bgMagenta.bold.white" \
    "bun run test --silent -- --watch=false" \
    "bun run --cwd \"$repo_root\" lint:all --silent" \
    "bun run --cwd \"$repo_root\" typecheck:all --silent" \
    "bun run build --silent"
