import { getMediaBaseUrl, images } from '#app/images.tsx'
import { getOptionalTeam } from './misc.ts'

export type CallKentEpisodeArtworkAvatar =
	| { kind: 'fetch'; url: string }
	| { kind: 'public'; publicId: string }

type CallKentEpisodeArtworkOptions = {
	title: string
	/**
	 * Display URL text rendered in the artwork (no protocol recommended).
	 * Example: "kentcdodds.com/calls/01/01"
	 */
	url: string
	/**
	 * Display name rendered in the artwork.
	 * Example: "- Kent"
	 */
	name: string
	/**
	 * Avatar used in the artwork.
	 * - Use `fetch` for remote images (ex: Gravatar).
	 * - Use `public` for in-platform media assets (ex: Kody) to keep URLs short.
	 */
	avatar: CallKentEpisodeArtworkAvatar
	/**
	 * Whether to apply a circular crop (`r_max`) to the avatar layer.
	 * Generally true for real photos, false for illustrations.
	 */
	avatarIsRound: boolean
	/**
	 * Output image dimensions (square). Defaults to 3000 like production.
	 *
	 * Note: The artwork layout is designed at 3000x3000 (to match publish-time
	 * uploads). Smaller sizes are generated by scaling the final result down so
	 * the preview matches production layout.
	 */
	size?: number
}

const DESIGN_SIZE = 3000
const KODY_PROFILE_BY_TEAM = {
	RED: images.kodyProfileRed,
	BLUE: images.kodyProfileBlue,
	YELLOW: images.kodyProfileYellow,
	UNKNOWN: images.kodyProfileGray,
} as const

export function getCallKentEpisodeArtworkAvatar({
	isAnonymous,
	team,
	gravatarUrl,
}: {
	isAnonymous: boolean
	team: string
	gravatarUrl?: string | null
}): CallKentEpisodeArtworkAvatar {
	if (isAnonymous) {
		return { kind: 'public', publicId: images.kodyProfileGray.id }
	}

	if (gravatarUrl) {
		return { kind: 'fetch', url: gravatarUrl }
	}

	const teamKey = getOptionalTeam(team)
	return {
		kind: 'public',
		publicId: KODY_PROFILE_BY_TEAM[teamKey].id,
	}
}

/**
 * Generates the media URL for Call Kent episode artwork.
 *
 * Keep this in sync with the publish-time artwork generation so the "preview"
 * shown to callers matches what ultimately gets uploaded to Transistor.
 */
export function getCallKentEpisodeArtworkUrl({
	title,
	url,
	name,
	avatar,
	avatarIsRound,
	size = DESIGN_SIZE,
}: CallKentEpisodeArtworkOptions) {
	const mediaBaseUrl = getMediaBaseUrl().replace(/\/+$/, '')
	const artworkUrl = new URL(`${mediaBaseUrl}/artwork/call-kent.png`)
	artworkUrl.searchParams.set('title', title)
	artworkUrl.searchParams.set('url', url)
	artworkUrl.searchParams.set('name', name)
	artworkUrl.searchParams.set('size', String(size))
	artworkUrl.searchParams.set('designSize', String(DESIGN_SIZE))
	artworkUrl.searchParams.set('avatarRound', avatarIsRound ? '1' : '0')
	artworkUrl.searchParams.set('avatarKind', avatar.kind)
	artworkUrl.searchParams.set(
		'avatar',
		avatar.kind === 'public' ? avatar.publicId : avatar.url,
	)
	return artworkUrl.toString()
}
