export const callKentTextToSpeechConstraints = {
	questionText: {
		minLength: 20,
		// Roughly sized so most questions land under ~2 minutes.
		maxLength: 2000,
	},
	// UI and submission safety limit; actual audio length depends on voice and pacing.
	maxAudioDurationSeconds: 120,
} as const

export const AI_VOICE_DISCLOSURE_PREFIX = `This caller's voice was generated by AI.`

// @cf/deepgram/aura-2-en: 3 male + 3 female voices (Deepgram featured + model default)
const auraSpeakers = [
	'apollo',
	'arcas',
	'orion',
	'luna',
	'andromeda',
	'helena',
] as const

export type CallKentTextToSpeechVoice = (typeof auraSpeakers)[number]

export const callKentTextToSpeechVoices: Array<{
	id: CallKentTextToSpeechVoice
	label: string
}> = auraSpeakers.map((speaker) => ({
	id: speaker,
	label: speaker.charAt(0).toUpperCase() + speaker.slice(1),
}))

export function isCallKentTextToSpeechVoice(
	voice: string,
): voice is CallKentTextToSpeechVoice {
	return (auraSpeakers as readonly string[]).includes(voice)
}

export function getErrorForCallKentQuestionText(value: string | null) {
	if (!value) return 'Question text is required'
	const text = value.trim()
	if (!text) return 'Question text is required'

	const { minLength, maxLength } = callKentTextToSpeechConstraints.questionText
	if (text.length < minLength) {
		return `Question text must be at least ${minLength} characters`
	}
	if (text.length > maxLength) {
		return `Question text must be no longer than ${maxLength} characters`
	}
	return null
}
