import { images } from '#app/images.tsx'
import { getOptionalTeam, toBase64 } from './misc.tsx'

export type CallKentEpisodeArtworkAvatar =
	| { kind: 'fetch'; url: string }
	| { kind: 'public'; publicId: string }

type CallKentEpisodeArtworkOptions = {
	title: string
	/**
	 * Display URL text rendered in the artwork (no protocol recommended).
	 * Example: "kentcdodds.com/calls/01/01"
	 */
	url: string
	/**
	 * Display name rendered in the artwork.
	 * Example: "- Kent"
	 */
	name: string
	/**
	 * Avatar used in the artwork.
	 * - Use `fetch` for remote images (ex: Gravatar).
	 * - Use `public` for Cloudinary assets (ex: Kody) to keep URLs short.
	 */
	avatar: CallKentEpisodeArtworkAvatar
	/**
	 * Whether to apply a circular crop (`r_max`) to the avatar layer.
	 * Generally true for real photos, false for illustrations.
	 */
	avatarIsRound: boolean
	/**
	 * Output image dimensions (square). Defaults to 3000 like production.
	 *
	 * Note: The artwork layout is designed at 3000x3000 (to match publish-time
	 * uploads). Smaller sizes are generated by scaling the final result down so
	 * the preview matches production layout.
	 */
	size?: number
}

const DESIGN_SIZE = 3000
const KODY_PROFILE_BY_TEAM = {
	RED: images.kodyProfileRed,
	BLUE: images.kodyProfileBlue,
	YELLOW: images.kodyProfileYellow,
	UNKNOWN: images.kodyProfileGray,
} as const

// Cloudinary needs double-encoding for `l_text:` payloads.
function doubleEncode(s: string) {
	return encodeURIComponent(encodeURIComponent(s))
}

export function getCallKentEpisodeArtworkAvatar({
	isAnonymous,
	team,
	gravatarUrl,
}: {
	isAnonymous: boolean
	team: string
	gravatarUrl?: string | null
}): CallKentEpisodeArtworkAvatar {
	if (isAnonymous) {
		return { kind: 'public', publicId: images.kodyProfileGray.id }
	}

	if (gravatarUrl) {
		return { kind: 'fetch', url: gravatarUrl }
	}

	const teamKey = getOptionalTeam(team)
	return {
		kind: 'public',
		publicId: KODY_PROFILE_BY_TEAM[teamKey].id,
	}
}

/**
 * Generates the Cloudinary URL for Call Kent episode artwork.
 *
 * Keep this in sync with the publish-time artwork generation so the "preview"
 * shown to callers matches what ultimately gets uploaded to Transistor.
 */
export function getCallKentEpisodeArtworkUrl({
	title,
	url,
	name,
	avatar,
	avatarIsRound,
	size = DESIGN_SIZE,
}: CallKentEpisodeArtworkOptions) {
	const outputSize = size
	const encodedTitle = doubleEncode(title)
	const encodedUrl = doubleEncode(url)
	const encodedName = doubleEncode(name)

	const avatarLayer =
		avatar.kind === 'public'
			? `l_${avatar.publicId.replace(/\//g, ':')}`
			: `l_fetch:${encodeURIComponent(toBase64(avatar.url))}`
	const radius = avatarIsRound ? ',r_max' : ''

	const textLines = Number(Math.ceil(Math.min(title.length, 50) / 18).toFixed())
	const avatarYPosition = textLines + 0.6
	const nameYPosition = -textLines + 5.2

	// Keep layout math consistent by always composing at 3000px, then scaling
	// for previews. Generating the layout directly at small sizes can crop out
	// content due to the underlying background asset being non-square.
	const vars = `$th_${DESIGN_SIZE},$tw_${DESIGN_SIZE},$gw_$tw_div_12,$gh_$th_div_12`

	const baseTransforms = [
		`https://res.cloudinary.com/kentcdodds-com/image/upload`,
		vars,
		`w_$tw,h_$th,l_kentcdodds.com:social-background`,
		`co_white,c_fit,g_north_west,w_$gw_mul_6,h_$gh_mul_2.6,x_$gw_mul_0.8,y_$gh_mul_0.8,l_text:kentcdodds.com:Matter-Medium.woff2_180:${encodedTitle}`,
		`c_crop${radius},g_north_west,h_$gh_mul_5.5,w_$gh_mul_5.5,x_$gw_mul_0.8,y_$gh_mul_${avatarYPosition},${avatarLayer}`,
		`co_rgb:a9adc1,c_fit,g_south_west,w_$gw_mul_8,h_$gh_mul_4,x_$gw_mul_0.8,y_$gh_mul_0.8,l_text:kentcdodds.com:Matter-Regular.woff2_120:${encodedUrl}`,
		`co_rgb:a9adc1,c_fit,g_south_west,w_$gw_mul_8,h_$gh_mul_4,x_$gw_mul_0.8,y_$gh_mul_${nameYPosition},l_text:kentcdodds.com:Matter-Regular.woff2_140:${encodedName}`,
		`c_fit,g_east,w_$gw_mul_11,h_$gh_mul_11,x_$gw,l_kentcdodds.com:illustrations:mic`,
	]

	// Preserve the exact publish-time URL for production uploads.
	if (outputSize === DESIGN_SIZE) {
		return [
			...baseTransforms,
			`c_fill,w_$tw,h_$th/kentcdodds.com/social-background.png`,
		].join('/')
	}

	return [
		...baseTransforms,
		`c_fill,w_$tw,h_$th`,
		`c_scale,w_${outputSize},h_${outputSize}`,
		`kentcdodds.com/social-background.png`,
	].join('/')
}
