"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.appendTxNumberCookie = exports.handleTransactionalConsistency = exports.getReplayResponse = exports.ensureInstance = exports.ensurePrimary = exports.getAllInstances = exports.getInternalInstanceDomain = exports.checkCookieForTransactionalConsistency = exports.getTxSetCookieHeader = exports.getTxNumber = exports.waitForUpToDateTxNumber = exports.TXID_NUM_COOKIE_NAME = exports.getInstanceInfoSync = exports.getInstanceInfo = void 0;
var litefs_js_1 = require("litefs-js");
Object.defineProperty(exports, "getInstanceInfo", { enumerable: true, get: function () { return litefs_js_1.getInstanceInfo; } });
Object.defineProperty(exports, "getInstanceInfoSync", { enumerable: true, get: function () { return litefs_js_1.getInstanceInfoSync; } });
Object.defineProperty(exports, "TXID_NUM_COOKIE_NAME", { enumerable: true, get: function () { return litefs_js_1.TXID_NUM_COOKIE_NAME; } });
Object.defineProperty(exports, "waitForUpToDateTxNumber", { enumerable: true, get: function () { return litefs_js_1.waitForUpToDateTxNumber; } });
Object.defineProperty(exports, "getTxNumber", { enumerable: true, get: function () { return litefs_js_1.getTxNumber; } });
Object.defineProperty(exports, "getTxSetCookieHeader", { enumerable: true, get: function () { return litefs_js_1.getTxSetCookieHeader; } });
Object.defineProperty(exports, "checkCookieForTransactionalConsistency", { enumerable: true, get: function () { return litefs_js_1.checkCookieForTransactionalConsistency; } });
Object.defineProperty(exports, "getInternalInstanceDomain", { enumerable: true, get: function () { return litefs_js_1.getInternalInstanceDomain; } });
Object.defineProperty(exports, "getAllInstances", { enumerable: true, get: function () { return litefs_js_1.getAllInstances; } });
var remix_1 = require("litefs-js/remix");
Object.defineProperty(exports, "ensurePrimary", { enumerable: true, get: function () { return remix_1.ensurePrimary; } });
Object.defineProperty(exports, "ensureInstance", { enumerable: true, get: function () { return remix_1.ensureInstance; } });
Object.defineProperty(exports, "getReplayResponse", { enumerable: true, get: function () { return remix_1.getReplayResponse; } });
Object.defineProperty(exports, "handleTransactionalConsistency", { enumerable: true, get: function () { return remix_1.handleTransactionalConsistency; } });
Object.defineProperty(exports, "appendTxNumberCookie", { enumerable: true, get: function () { return remix_1.appendTxNumberCookie; } });
