import {
	createRequestHandler,
	type AppLoadContext,
	type ServerBuild,
} from 'react-router'
import { getEnv, setRuntimeEnvSource } from '../../site/app/utils/env.server.ts'
import {
	setRuntimeBindingSource,
	type RuntimeBindingSource,
} from '../../site/app/utils/runtime-bindings.server.ts'

type AssetsBinding = {
	fetch(request: Request): Response | Promise<Response>
}

type WorkerEnv = RuntimeBindingSource & {
	ASSETS?: AssetsBinding
}

type SiteRequestHandler = (
	request: Request,
	loadContext?: AppLoadContext,
) => Promise<Response>

type HandleRequestOptions = {
	createCspNonce?: () => string
	getServerBuild?: () => Promise<ServerBuild>
	mode?: string
}

type ErrorResponse = {
	ok: false
	error: string
}

type HealthResponse = {
	ok: true
}

function json(data: ErrorResponse | HealthResponse, init?: ResponseInit) {
	return Response.json(data, init)
}

function methodNotAllowed() {
	return json(
		{ ok: false, error: 'Method not allowed' },
		{ status: 405, headers: { Allow: 'GET' } },
	)
}

let cachedRequestHandlers = new Map<string, SiteRequestHandler>()

export async function handleRequest(
	request: Request,
	env: WorkerEnv = {},
	ctx: ExecutionContext | undefined = undefined,
	options: HandleRequestOptions = {},
) {
	const url = new URL(request.url)
	bootstrapRuntimeSources(env)

	if (url.pathname === '/health') {
		if (request.method !== 'GET') return methodNotAllowed()
		return json({ ok: true })
	}

	const assetResponse = await maybeServeAsset(request, env)
	if (assetResponse) return assetResponse

	const requestHandler = await getRequestHandler(request, options)
	return await requestHandler(request, {
		cloudflare: { env, ctx },
		cspNonce: options.createCspNonce?.() ?? createCspNonce(),
	} as AppLoadContext)
}

export default {
	async fetch(request: Request, env: WorkerEnv, ctx: ExecutionContext) {
		return await handleRequest(request, env, ctx)
	},
} satisfies ExportedHandler<WorkerEnv>

async function getRequestHandler(
	request: Request,
	{ getServerBuild, mode = 'production' }: HandleRequestOptions,
) {
	if (getServerBuild) {
		return createRequestHandler(
			await getServerBuild(),
			mode,
		) as SiteRequestHandler
	}

	const cacheKey = `${mode}:${new URL(request.url).host}`
	let requestHandler = cachedRequestHandlers.get(cacheKey)
	if (!requestHandler) {
		requestHandler = createRequestHandler(
			await getDefaultServerBuild(request),
			mode,
		) as SiteRequestHandler
		cachedRequestHandlers.set(cacheKey, requestHandler)
	}
	return requestHandler
}

async function getDefaultServerBuild(request: Request) {
	const build =
		// @ts-ignore - generated by `npm run build:site --workspace site-worker`.
		(await import('../../site/build/server/index.js')) as ServerBuild
	return {
		...build,
		allowedActionOrigins: getWorkerAllowedActionOrigins(request),
	} satisfies ServerBuild
}

export function getWorkerAllowedActionOrigins(request: Request) {
	const requestHost = new URL(request.url).host
	return Array.from(new Set([...getEnv().allowedActionOrigins, requestHost]))
}

function bootstrapRuntimeSources(env: WorkerEnv) {
	setRuntimeEnvSource(getStringEnvBindings(env))
	setRuntimeBindingSource(env)
}

function getStringEnvBindings(env: WorkerEnv) {
	return Object.fromEntries(
		Object.entries(env).filter((entry): entry is [string, string] => {
			return typeof entry[1] === 'string'
		}),
	)
}

async function maybeServeAsset(request: Request, env: WorkerEnv) {
	if (request.method !== 'GET' && request.method !== 'HEAD') return null
	if (!env.ASSETS) return null

	const response = await env.ASSETS.fetch(request)
	if (response.status === 404) return null
	return response
}

function createCspNonce() {
	const bytes = new Uint8Array(16)
	crypto.getRandomValues(bytes)
	return Array.from(bytes, (byte) => byte.toString(16).padStart(2, '0')).join(
		'',
	)
}
