export type Env = {
	CALL_KENT_AUDIO_CONTAINER_URL: string
	CALL_KENT_AUDIO_CONTAINER_TOKEN: string
	CALL_KENT_AUDIO_CALLBACK_URL: string
	CALL_KENT_AUDIO_CALLBACK_SECRET: string
	CALL_KENT_AUDIO_BUCKET: R2Bucket
	CLOUDFLARE_API_TOKEN: string
	CLOUDFLARE_AI_GATEWAY_AUTH_TOKEN: string
	CLOUDFLARE_AI_GATEWAY_ID: string
	CLOUDFLARE_AI_TRANSCRIPTION_MODEL: string
	CLOUDFLARE_AI_CALL_KENT_METADATA_MODEL: string
	CLOUDFLARE_AI_CALL_KENT_TRANSCRIPT_FORMAT_MODEL: string
}
