import { type ServerBuild } from 'react-router'
import { setRuntimeEnvSource } from '../../../site/app/utils/env.server.ts'
import { setRuntimeBindingSource } from '../../../site/app/utils/runtime-bindings.server.ts'
import { formatColdStartTiming } from '../cold-start-timing.ts'
import redirectsText from '../../../site/other/_redirects.txt'
import {
	createWorkerFetchHandler,
	getStringEnvBindings,
	type WorkerEnv,
} from '../../../site/app/utils/worker-request-pipeline.server.ts'

let isolateId: string | undefined

function getIsolateId() {
	if (!isolateId) isolateId = crypto.randomUUID()
	return isolateId
}

let contentDataPromise: Promise<unknown> | null = null
let bridgesInitialized = false
let firstRequestTimings: Record<string, number> | null = null
let cachedServerBuild: ServerBuild | null = null

async function ensureRuntimeBridges(env: WorkerEnv) {
	if (bridgesInitialized) return
	const bridgesStartedAt = performance.now()
	setRuntimeEnvSource(getStringEnvBindings(env))
	setRuntimeBindingSource(env)

	const contentDataKey = Symbol.for('kentcdodds.contentData')
	const loadMdxModuleKey = Symbol.for('kentcdodds.loadMdxModule')

	if (!contentDataPromise) {
		contentDataPromise = import('site-content-data.json').then(
			(mod) => mod.default,
		)
	}
	const contentImportStartedAt = performance.now()
	const contentData = await contentDataPromise
	const contentImportMs = performance.now() - contentImportStartedAt
	;(globalThis as Record<symbol, unknown>)[contentDataKey] = contentData
	;(globalThis as Record<symbol, unknown>)[loadMdxModuleKey] = async (
		contentDir: string,
		slug: string,
	) => {
		try {
			return await import(`mdx/${contentDir}/${slug}.js`)
		} catch (error: unknown) {
			console.error(
				`loadMdxModule failed for mdx/${contentDir}/${slug}.js`,
				error,
			)
			return null
		}
	}
	bridgesInitialized = true
	if (!firstRequestTimings) {
		firstRequestTimings = {
			bridges: performance.now() - bridgesStartedAt,
			contentImport: contentImportMs,
		}
	}
}

function decorateResponseHeaders(
	headers: Headers,
	timing: {
		requestStartedAtPerfNow: number
		handlerReadyMs?: number
		handlerServeMs?: number
	},
) {
	headers.set('X-Isolate-Id', getIsolateId())
	if (firstRequestTimings) {
		headers.set(
			'X-Cold-Start-Timing',
			formatColdStartTiming({
				...firstRequestTimings,
				...(timing.handlerReadyMs === undefined
					? {}
					: { handlerReady: timing.handlerReadyMs }),
				...(timing.handlerServeMs === undefined
					? {}
					: { handlerServe: timing.handlerServeMs }),
				request: performance.now() - timing.requestStartedAtPerfNow,
			}),
		)
		firstRequestTimings = null
	}
}

export default createWorkerFetchHandler({
	redirectsText,
	ensureRuntimeBridges,
	decorateResponseHeaders,
	requestHandlerMode: 'production',
	errorLogLabel: 'app-worker fetch failed',
	async getServerBuild() {
		if (!cachedServerBuild) {
			const handlerImportStartedAt = performance.now()
			cachedServerBuild = (await import(
				// @ts-ignore -- generated by `npm run build:site --workspace site-worker`;
				// absent in environments (like CI validate) that typecheck without building.
				'../../../site/build/server/index.js'
			)) as unknown as ServerBuild
			if (firstRequestTimings) {
				firstRequestTimings.handlerImport =
					performance.now() - handlerImportStartedAt
			}
		}
		return cachedServerBuild
	},
})
